export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
// 暂时没理解，回头再看看  暂时理解就是判断 INCREMENT_ENTHUSIASM 的类型 string
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;